class CreateFcdata < ActiveRecord::Migration[5.0]
  def change
    create_table :fcdata do |t|
      t.string :custserial,  null:false
      t.string :faceno
      t.string :measuredate
      t.integer :measureno
      t.string :uptdate
      t.float :mo_1
      t.float :mo_7
      t.float :mo_8
      t.integer :pr_1
      t.integer :pr_2
      t.integer :pr_7
      t.integer :pr_8
      t.integer :pr_avr
      t.integer :wr_3
      t.integer :wr_4
      t.integer :wr_5
      t.integer :wr_6
      t.integer :wr_avr
      t.integer :el_7
      t.integer :el_8
      t.integer :el_avr
      t.float :el_angle_7
      t.float :el_angle_8
      t.integer :sb_1
      t.integer :sb_2
      t.integer :sb_7
      t.integer :sb_8
      t.integer :sb_avr
      t.integer :pp_1
      t.integer :pp_2
      t.integer :pp_7
      t.integer :pp_8
      t.integer :pp_avr
      t.integer :pp_ratio_1
      t.integer :pp_ratio_2
      t.integer :pp_ratio_7
      t.integer :pp_ratio_8
      t.integer :pp_ratio_avr
      t.integer :sp_pl_1
      t.integer :sp_pl_2
      t.integer	:sp_pl_3
      t.integer :sp_pl_4
      t.integer :sp_pl_5
      t.integer :sp_pl_6
      t.integer :sp_pl_7
      t.integer :sp_pl_8
      t.integer :sp_pl_avr
      t.integer :sp_uv_1
      t.integer :sp_uv_2
      t.integer :sp_uv_3
      t.integer :sp_uv_4
      t.integer :sp_uv_5
      t.integer :sp_uv_6
      t.integer :sp_uv_7
      t.integer :sp_uv_8
      t.integer :sp_uv_avr
      t.integer	:sk_c_1
      t.integer :sk_c_2
      t.integer :sk_c_4
      t.integer :sk_c_6
      t.integer :sk_c_7
      t.integer	:sk_c_8
      t.integer	:sk_c_avr
      t.integer	:sk_r_1
      t.integer	:sk_r_2
      t.integer	:sk_r_4
      t.integer	:sk_r_6
      t.integer	:sk_r_7
      t.integer :sk_r_8
      t.integer :sk_r_avr
      t.integer	:sk_g_1
      t.integer	:sk_g_2
      t.integer	:sk_g_4
      t.integer	:sk_g_6
      t.integer	:sk_g_7
      t.integer :sk_g_8
      t.integer	:sk_g_avr
      t.integer	:sk_b_1
      t.integer	:sk_b_2
      t.integer	:sk_b_4
      t.integer	:sk_b_6
      t.integer	:sk_b_7
      t.integer	:sk_b_8
      t.integer	:sk_b_avr
      t.float	:lab_l
      t.float :lab_a
      t.float :lab_b
      t.integer :colortype
      t.integer :suntype
      t.integer :skintype
      t.integer :score_r
      t.integer :score_l
      t.integer :yanus_status, :default => 1

      t.timestamps
    end
  end
end
